### PR TITLE
Added description field for documentation

### PR DESCRIPTION
**Pull request by LIV2DRV**
Passing app.description such that OpenAPI includes the description in the documentation

### CODE REVIEW

**Comment by LIV2DRV** [comment]
Seems the CI workflow is failing on importing the example module.  Could you trigger it with master?  I'm assuming my one-line change wouldn't be causing the import error.

tests/test_example.py:3: in <module>
    from example.annotation.app import app as annotation_app
E   ModuleNotFoundError: No module named 'example'

**Comment by DeanWay** [comment]
Yeah, the problem is on the master build too. Something must have changed with travis-ci since the last time a build was run on this project. Looking into it

**Comment by DeanWay** [comment]
fixed 😄

**Comment by DeanWay** [comment]
released in version 0.5.0

**Pull request merged**
