### PR TITLE
:sparkles: Reflect attributes in version decorator

### LINKED ISSUE #11: Use functools.wraps for decorator
Implement functools.wraps in the `version` decorator to [avoid breaking tab completion](https://www.piccolo-orm.com/blog/improving-tab-completion-in-python-libraries/#decorators-can-be-deceiving) and breaking wrapped function signature:

https://github.com/DeanWay/fastapi-versioning/blob/875863c0a312e4d30ecbb351abc3e145fa203b62/fastapi_versioning/versioning.py#L12

### PR DESCRIPTION
**Pull request by HacKanCuBa**
Rewriting the decorator using functools.wraps() allows for tab completion
and correctly reflecting of attributes and signature of wrapped function.

Closes #11.

### CODE REVIEW

**Comment by takeda** [comment]
There are two issues with this:

1. you forgot `return wrapper`
2. your PR actually changes behavior of the decorator. After your change the assignment of version happens on every invocation, when previously it only happened once when the function was created.

I believe the original code is actually correct and the autocomplete works. Perhaps the types should be updated to ones suggested here: https://github.com/tiangolo/fastapi/issues/200#issuecomment-525126712 which should work in PyCharm at least.

**Comment by HacKanCuBa** [comment]
Damn, that's correct! Yeah, probably typing as suggested would work. I'm closing this PR :)

**Comment by takeda** [comment]
I still think a PR is needed to update types to similar to what was in that comment. Right now all it says is that argument and return is a function, which in case of a decorator that's not saying much.

**Comment by HacKanCuBa** [comment]
> I still think a PR is needed to update types to similar to what was in that comment (which is the recommend way https://mypy.readthedocs.io/en/stable/cheat_sheet_py3.html#decorators). Right now all it says is that argument and return is a function, which in case of a decorator that's not saying much.

Agree, will fix one like that on a different PR

**Pull request closed without merging**
