### PR TITLE
Add latest endpoint for the latest API version 

### LINKED ISSUE #35: Support for "latest" version?
We have a use case where our API is decoupled from services that call it, which would require another lengthy PR process for our monolith application to update the client to use the newer version of the API.

It would be great to be able to call `/api/latest/endpoint` or `/api/v/latest/endpoint` to automatically use the latest version of the API. This would allow the monolith client code to not have to be changed when we add a new minor/major version to our API.

### PR DESCRIPTION
**Pull request by patrickelectric**
Fix #35

### CODE REVIEW

**Comment by DeanWay** [comment]
thanks @patrickelectric. Looks good to me. My only thought is that this may not be something that everyone would want out of a versioned API? (perhaps if you're going through the trouble of versioning your API you wouldn't want to allow your clients to break out of specifying a version).

My thoughts for how to handle that would be:
1. make this configurable somehow
2. Expose the list of versions and just document the redirect endpoint you've added here as a recipe to optionally include in your own application

**Comment by patrickelectric** [comment]
Done @DeanWay, let me know what you think:
image

**Review by DeanWay — APPROVED** [review]
LTGM

**Comment by DeanWay** [comment]
the CI check is failing due to a lint error, I'll fix it on master

**Pull request merged**
